---
inputs:
  - type: git
    branch: ${PIPELINE_REPO_BRANCH}
    service: ${PIPELINE_REPO}
    path: .tekton

triggers:
  - type: git
    name: github-commit
    eventListener: eventlistener-git-trigger-github-commit
    service: ${PIPELINE_REPO}
    branch: ${PIPELINE_REPO_BRANCH}
    events: { "push": false }

  - type: manual
    name: Manual-Trigger
    eventListener: eventlistener-git-trigger-manual
    properties:
      - type: text
        name: branch
        value: ${PIPELINE_REPO_BRANCH}
    is_public_worker: true

properties:
  - name: repositoryForManualTrigger
    value: ${PIPELINE_REPO}
    type: integration
    path: parameters.repo_url
  - type: text
    name: pattern
    value: ${PATTERN}
  - type: secure
    name: apikey
    value: ${API_KEY}
  - type: text
    name: terraform-cmd
    value: "apply"
  - type: text
    name: pipeline-debug
    value: "false"
  - type: text
    name: schematics-wksp
    value: ${SCHEMATICS_WORKSPACE_NAME}
  - type: text
    name: app-cicd-webhookurl
    value: ${APP_CICD_WEBHOOKURL}
  - type: text
    name: app-cicd-header-key
    value: ${APP_CICD_HEADER_KEY}
  - type: secure
    name: app-cicd-token
    value: ${APP_CICD_TOKEN}
  

