---
inputs:
  - type: git
    branch: ${PIPELINE_REPO_BRANCH}
    service: ${PIPELINE_REPO}
    path: .tekton/destroy

triggers:
  - type: manual
    name: Manual-Trigger
    eventListener: eventlistener-git-trigger-manual
    properties:
    is_public_worker: true

properties:
  - type: text
    name: pipeline-debug
    value: "false"
  - type: secure
    name: apikey
    value: ${API_KEY}
  - type: text
    name: schematics-wksp
    value: ${SCHEMATICS_WORKSPACE_NAME}
  - type: text
    name: confirm-deletion
    value: "no"
  

